# Regresión lineal en Python

## El paquete scikit-learn para regresión lineal y la selección de *features*

In [17]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv("../../datasets/ads/Advertising.csv")
data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [3]:
feature_cols = ["TV","Radio","Newspaper"]

In [4]:
X = data[feature_cols]
Y = data["Sales"]

In [26]:
estimator = SVR(kernel = "linear")
selector  = RFE(estimator, 2, step = 1)
selector  = selector.fit(X, Y)

/home/mauricio/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


In [27]:
selector.support_ # Variables en el modelo

array([ True,  True, False])

In [12]:
selector.ranking_

array([1, 1, 2])

In [20]:
X_pred = X[["TV","Radio"]]
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression()

In [22]:
lm.coef_

array([0.04575482, 0.18799423])

In [23]:
lm.score(X_pred, Y)

0.8971942610828957