# El método K-means

In [23]:
import numpy as np
import pandas as pd
from scipy.cluster.vq import vq
from scipy.cluster.vq import kmeans

In [24]:
data = np.random.normal(size = 90).reshape(30,3)
data

array([[-0.48539085, -1.90515385, -0.5262218 ],
       [-0.31354602,  0.33070649,  0.93853725],
       [-0.56821116, -0.19377527,  1.31280484],
       [ 1.681251  , -0.76813595, -0.76311794],
       [-0.45737545, -2.15541652,  0.51516947],
       [ 0.37920962, -0.69993372,  0.7089239 ],
       [-0.34798538,  1.54588781,  0.54680904],
       [-1.284877  , -1.73820287, -0.51482514],
       [ 0.37004361, -1.71219704,  1.32854527],
       [ 0.85180451, -1.17732503,  1.12722017],
       [ 0.49599207,  1.33015894,  0.64812082],
       [-1.99832609,  0.34026654,  0.30297731],
       [-1.01807988,  0.36972476, -0.99125932],
       [ 1.17140585,  2.28693771,  1.10545818],
       [-0.56546254,  0.70761329,  0.16505748],
       [-0.73070227, -0.52965621, -0.59603401],
       [-0.65072001,  0.01757337, -0.86330093],
       [-0.85526903,  0.06352153, -2.24336739],
       [ 0.2619215 , -1.12931946, -0.56196398],
       [-1.03443857, -1.34825025, -1.86763833],
       [ 1.56425096, -1.74863733,  1.387

In [28]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1],data[c2]])
clust_centers

array([[-0.73070227, -0.52965621, -0.59603401],
       [ 1.56425096, -1.74863733,  1.3871611 ]])

In [30]:
vq(data, clust_centers)

(array([0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([1.39894431, 1.80807971, 1.94496404, 2.36617243, 1.98810897,
        1.72157311, 2.4000928 , 1.3320246 , 1.19620019, 0.94949829,
        2.55178616, 1.78097083, 1.02356   , 3.80082784, 1.46198503,
        0.        , 0.61423854, 1.75530168, 1.1601977 , 1.54250754,
        0.        , 1.54403542, 1.80523562, 1.57104714, 3.24504686,
        1.62697538, 0.64124068, 1.29059207, 1.45148281, 0.75265103]))

In [35]:
kmeans(data, 2)

(array([[-0.53989241,  0.77958744,  0.58311229],
        [ 0.04016545, -0.98941925, -0.27061644]]),
 1.2916913359605104)